[features]
seeds = false
skip-lint = false
[programs.devnet]
store = "GXgYN645MbNjUCmLyCsS6jikssTz1sUt3pn2wf5DjmBF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/oliverke/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
